name: Build Android APK/AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set Java 21 (to match Capacitor source release)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Set up Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      # 4️⃣ Cache Gradle for faster builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 5️⃣ Build APK & AAB without worrying about local Java
      - name: Build APK & AAB
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease bundleRelease

      # 6️⃣ Upload APK & AAB artifacts
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MyCapApp-release
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
